version: "3.9"

services:

  backend:
    build: ./BACKEND
    container_name: avisena-backend
    restart: always
    environment:
      - PORT=8000
      - UVICORN_HOST=0.0.0.0
    expose:
      - "8000"

  frontend:
    build: ./FRONTEND
    container_name: avisena-frontend
    restart: always
    expose:
      - "80"
